python basic1.py
python tensor-elem1.py
python tensor-elem2.py
python tensor-elem3.py
python tf-const.py
python tf-const2.py
python tf-cpu.py
#python tf-gpu.py
python tf-math-ops.py
python tf-save-data.py
python tf-var-multiply.py
