import tensorflow as tf

a1 = tf.constant(5)
a2 = tf.constant([5])
a3 = tf.constant([5,])
b1 = tf.constant([5,9,])
c1 = tf.constant([[5,9],[12, 25,],])
#c2 = tf.constant([[5,9,7],[12, 25,],])
s1 = tf.constant("hello")

print("a1:",a1)
print("a2:",a2)
print("a3:",a3)
print("b1:",b1)
print("c1:",c1)
print("s1:",s1)
print("")

print("type a1:",type(a1))
print("type a2:",type(a2))
print("type a3:",type(a3))
print("type b1:",type(b1))
print("type c1:",type(c1))
print("type s1:",type(s1))
print("")

sess = tf.Session() 
print("a1:",sess.run(a1))
print("a2:",sess.run(a2))
print("a3:",sess.run(a3))
print("b1:",sess.run(b1))
print("c1:",sess.run(c1))
print("s1:",sess.run(s1))
print("")
